### DISCUSSION TITLE
Allow multiple databases in PostgresUser CR

### DISCUSSION THREAD

**Discussion by toboshii** [movetokube/postgres-operator#201] [Ideas]
First off, loving many things about this operator but one issue I ran into trying to migrate some things to it is that I have a few third party apps I run in my cluster that are designed in a way in which they need multiple Postgres databases (not schemas, completely separate databases) but only allow for a single hostname, username, password config. Afaict there's no way for ext-postgres-operator to handle this currently.

Ideally I'd like to be able to do something like this:
```yaml
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: radarr-config-db
  namespace: media
spec:
  database: radarr-config
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: radarr-log-db
  namespace: media
spec:
  database: radarr-log
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: radarr-user
  namespace: media
spec:
  role: radarr
  databases:
    - name: radarr-config-db
      privileges: OWNER
    - name: radarr-log-db
      privileges: OWNER
  secretName: database
---
```
and would expect the `database-radarr-user` secret created to contain a role the has the referenced privileges on both referenced databases.

**Comment by michalschott** [comment]
On top of that, I'd even say it would be handy to have some sort of PostgresqlClass to run multiple instances of this operator in single cluster to handle multiple lets say RDS clusters.

**Reply by tkcontiant** [reply]
PostgresqlClass already exists.

```
postgres.db.movetokube.com/instance: operator-instance-name
```

**Comment by TheAceMan** [comment]
This would require changes to the secret that is created. For backward compatibility if there is just one database secret naming could remain the same. But if there are multiple databases then the secret would contain the database name in the secret name.

**Comment by adepssimius** [comment]
I had the exact same problem. I have a functional example of how this would work. The readme is updated with the new CRD shape, which I lifted pretty much verbatim from here. I built an image and it's currently up at `ghcr.io/adepssimius/postgres-operator:2.1.0-alpha-2`. All changes are currently in my fork here: https://github.com/adepssimius/postgres-operator/tree/multi-db-user and I have tested and confirmed that I am able to create 2 DBs and a role that owns them by pushing the following:

```
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: foo-db
  namespace: my-app
spec:
  database: foo
  dropOnDelete: true
  schemas:
  - alice
  - bob
  extensions:
  - postgis
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: bar-db
  namespace: my-app
spec:
  database: bar
  dropOnDelete: true
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: my-user
  namespace: my-app
spec:
  role: app
  databases:
    - name: foo-db
      privileges: OWNER
    - name: bar-db
      privileges: OWNER
  secretName: my-user-db
  ```
  
 The result was the 2 DBs and the role were created, along with the secret containing credentials for that role. The only thing that I had trouble with was that I don't think that the schemas that were created for foo were correctly owned by the role that was created for the postgres user. For *arr apps I don't think this is an issue since the migrations should handle creating the schemas.
 
 Disclaimer that openAI codex did a lot of heavy lifting here. While I do write and review code for my day job, I don't use golang. Reading through the resulting AI edits, everything seemed to be organized and named sensibly.
