### ISSUE TITLE
Break database and user role creation apart

### ISSUE THREAD

**Issue by arnarg** [movetokube/postgres-operator#3]
Currently you can't have users for the same database in more than one namespace. The role will be created in the second namespace but it won't get any privileges. This can be fixed by simply not returning from `CreateDB` on duplicate database error but I think there are more perks to splitting them apart.

So here's my idea:
```
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: my-db
  namespace: app
spec:
  database: test-db
```

This obviously creates the db `test-db` in postgres and a group role `test-db-group` that becomes the owner of the database.

```
CREATE ROLE test-db-group;
CREATE DATABASE test-db OWNER test-db-group;
```

```
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: my-db-user
  namespace: app
spec:
  role: test-db-user
  database: test-db
  secretName: test-db-postgres-user
```

This will create a user role `test-db-user` in postgres and then grant `test-db-group` to `test-db-user`.

```
CREATE ROLE test-db-user WITH LOGIN PASSWORD '<random>';
GRANT test-db-group TO test-db-user;
```

The `PostgresUser` CRD could even be extended to give us more powerful options.

```
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: my-db-user
  namespace: app
spec:
  role: test-db-user
  databases:
  - name: test-db
    privileges:
    - OWNER
  - name: another-db
    privileges:
    - SELECT
    - INSERT
  secretName: test-db-postgres-user
```

```
CREATE ROLE test-db-user WITH LOGIN PASSWORD '<random>';
GRANT test-db-group TO test-db-user;
GRANT SELECT ON DATABASE another-db TO test-db-user;
GRANT INSERT ON DATABASE another-db TO test-db-user;
```
