### ISSUE TITLE
full test coverage

### ISSUE THREAD

**Issue by hitman99** [movetokube/postgres-operator#31]
Currently there are no tests of any kind for the operator code, this issue addresses that. Test coverage should be at least 80% Just unit tests are fine as integration tests might be a bit tricky to do.

**Comment by arnarg** [comment]
I've been thinking about this as well. This will be a bit tricky as most of our business logic depends on a database being there and is PostgreSQL specific.

Do you have any plan of attack?

**Comment by hitman99** [comment]
For operator controller(s) logic, we could use mocked PG package, which we could generate. As for the actual Postgres package, we'd have to use integration tests, running tests in docker-compose where we could use real postgres database, in a container. Another and probably easier option would be to use github actions as it supports services (like Gitlab CI Services), where we could configure something like this for integration tests:
```yaml
jobs:
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
```
Which oiption do you prefer? This will not be easy as for some queries we'd need to write more queries in tests to check if it worked or not.
