### ISSUE TITLE
Can't delete PostgresUser CR after deleting Postgres CR

### ISSUE THREAD

**Issue by oxyno-zeta** [movetokube/postgres-operator#44]
**Describe the bug**
The bug is following:
If you have deleted the Postgres CR linked to PostgresUser CR, you can't properly delete a PostgresUser anymore. The operator will loop over an error in case `dropOnDelete` is set to `true` or at restart, it will crash.

**To Reproduce**
1. Create a Postgres CR
```yaml
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: my-db
  namespace: app
spec:
  database: test-db # Name of database created in PostgreSQL
  dropOnDelete: true # Set to true if you want the operator to drop the database and role when this CR is deleted
```
2. Create a PostgresUser CR
```yaml
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: my-db-user
  namespace: app
spec:
  role: username
  database: my-db # This references the Postgres CR
  secretName: my-secret
  privileges: OWNER # Can be OWNER/READ/WRITE
```
3. Delete Postgres CR
4. Delete PostgresUser CR
5. See error

**Expected behavior**
For me, an expected behaviour should be to delete all PostgresUser linked to a Postgres CR when this one is deleted.

**Screenshots**
None

**Version and platform (please complete the following information):**
 - Platform [e.g. Linux, Mac, Windows, ...]: Linux
 - Arch [e.g. amd64, ...]: amd64
 - Version [e.g. 22]: 0.4.2

**Additional context**
None
