### ISSUE TITLE
Image should have tag to avoid using latest

### ISSUE THREAD

**Issue by endersonmaia** [movetokube/postgres-operator#78]
For security and reproducibility of deploys, the operator container image should use a tagged one.

https://github.com/movetokube/postgres-operator/blob/master/deploy/operator.yaml#L18

```yaml
...
      containers:
        - name: ext-postgres-operator
          image: movetokube/postgres-operator:0.5.2
...
```
